-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 09:51:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DiagnosticCenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DiagnosticCenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiagnosticCenter` DEFAULT CHARACTER SET utf8 ;
USE `DiagnosticCenter` ;

-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`User` (
  `idUser` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` LONGTEXT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Activation` TINYINT NOT NULL,
  `Image` BLOB NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Patient` (
  `idPatient` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `Sex` VARCHAR(10) NOT NULL,
  `BloodGroup` VARCHAR(5) NULL,
  `DateOfBirth` DATE NULL,
  `MobileNo` VARCHAR(15) NOT NULL,
  `Address` VARCHAR(200) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Patient_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `DiagnosticCenter`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Doctor` (
  `idDoctor` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NULL,
  `Degree` VARCHAR(250) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idDoctor`),
  INDEX `fk_Doctor_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Doctor_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `DiagnosticCenter`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Pathologist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Pathologist` (
  `idPathologist` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Speciality` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPathologist`),
  INDEX `fk_Pathologist_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Pathologist_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `DiagnosticCenter`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Prescription` (
  `idPrescription` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Problem` VARCHAR(300) NULL,
  `Patient_idPatient` INT NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idPrescription`, `Patient_idPatient`, `Doctor_idDoctor`),
  INDEX `fk_Prescription_Patient1_idx` (`Patient_idPatient` ASC),
  INDEX `fk_Prescription_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Prescription_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `DiagnosticCenter`.`Patient` (`idPatient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `DiagnosticCenter`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Test` (
  `idTest` INT NOT NULL,
  `TestName` VARCHAR(100) NOT NULL,
  `Prescription_idPrescription` INT NOT NULL,
  `Prescription_Patient_idPatient` INT NOT NULL,
  `Prescription_Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idTest`, `Prescription_idPrescription`, `Prescription_Patient_idPatient`, `Prescription_Doctor_idDoctor`),
  INDEX `fk_Test_Prescription1_idx` (`Prescription_idPrescription` ASC, `Prescription_Patient_idPatient` ASC, `Prescription_Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Test_Prescription1`
    FOREIGN KEY (`Prescription_idPrescription` , `Prescription_Patient_idPatient` , `Prescription_Doctor_idDoctor`)
    REFERENCES `DiagnosticCenter`.`Prescription` (`idPrescription` , `Patient_idPatient` , `Doctor_idDoctor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`PrescribedMedicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`PrescribedMedicine` (
  `idPrescribedMedicine` INT NOT NULL,
  `Medicine` VARCHAR(100) NOT NULL,
  `Dosage` VARCHAR(45) NOT NULL,
  `Use` VARCHAR(45) NULL,
  `Prescription_idPrescription` INT NOT NULL,
  `Prescription_Patient_idPatient` INT NOT NULL,
  `Prescription_Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idPrescribedMedicine`, `Prescription_idPrescription`, `Prescription_Patient_idPatient`, `Prescription_Doctor_idDoctor`),
  INDEX `fk_PrescribedMedicine_Prescription1_idx` (`Prescription_idPrescription` ASC, `Prescription_Patient_idPatient` ASC, `Prescription_Doctor_idDoctor` ASC),
  CONSTRAINT `fk_PrescribedMedicine_Prescription1`
    FOREIGN KEY (`Prescription_idPrescription` , `Prescription_Patient_idPatient` , `Prescription_Doctor_idDoctor`)
    REFERENCES `DiagnosticCenter`.`Prescription` (`idPrescription` , `Patient_idPatient` , `Doctor_idDoctor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Admin` (
  `idAdmin` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `fk_Admin_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Admin_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `DiagnosticCenter`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`Appointment` (
  `idAppointment` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Time` VARCHAR(45) NOT NULL,
  `Patient_idPatient` INT NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idAppointment`, `Patient_idPatient`, `Doctor_idDoctor`),
  INDEX `fk_Appointment_Patient1_idx` (`Patient_idPatient` ASC),
  INDEX `fk_Appointment_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `DiagnosticCenter`.`Patient` (`idPatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `DiagnosticCenter`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`AppointmentTimeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`AppointmentTimeTable` (
  `idAppointmentTimeTable` INT NOT NULL,
  `Time` VARCHAR(45) NOT NULL,
  `OffDay` VARCHAR(45) NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idAppointmentTimeTable`),
  INDEX `fk_AppointmentTimeTable_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_AppointmentTimeTable_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `DiagnosticCenter`.`Doctor` (`idDoctor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticCenter`.`TestReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DiagnosticCenter`.`TestReport` (
  `idTestReport` INT NOT NULL,
  `Observation` VARCHAR(100) NULL,
  `Result` VARCHAR(45) NULL,
  `Test_idTest` INT NOT NULL,
  `ReportDocument` BLOB NULL,
  PRIMARY KEY (`idTestReport`),
  INDEX `fk_TestReport_Test1_idx` (`Test_idTest` ASC),
  CONSTRAINT `fk_TestReport_Test1`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `DiagnosticCenter`.`Test` (`idTest`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
